/*
 *  Copyright 2026 - Patrick Head
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 *  @file attribute.h
 *  @brief functions to manage attribute data
 *
 *  This file was generated by kahdifire
 */

#ifndef ATTRIBUTE_H
#define ATTRIBUTE_H

#include <stdbool.h>
#include <stdint.h>

    /*
     *  Typedefs for all declared enums, structs and unions
     */

  /**
   *  @typedef attribute
   *  @brief creates a type for @a attribute struct
   */

typedef struct attribute attribute;

  /**
   *  @typedef attribute_array
   *  @brief creates a type for @a attribute_array struct
   */

typedef struct attribute_array attribute_array;

    /*
     *  Declarations for all enums, structs and unions
     */

  /**
   *  @typedef enum attribute_visibility
   *  @brief creates a type for enum @a attribute_visibility and values
   */

typedef enum
{
  attribute_visibility_value = 0,  /**< display only value */
  attribute_visibility_both = 1,  /**< display both name and value */
  attribute_visibility_none = 2  /**< do not display name or value */
} attribute_visibility;

  /**
   *  @struct attribute
   *  @brief declares struct @a attribute
   */

struct attribute
{
  char *name;  /**<  name of attribute */
  char *value;  /**<  value of attribute */
  attribute_visibility visibility;  /**<  display visibility of attribute */
};

  /**
   *  @struct attribute_array
   *  @brief struct used to manage a dynamic array of @a attribute structs
   */

struct attribute_array
{
  int n;             /**<  number of items in array         */
  int current;       /**<  index of current item in array   */
  attribute **item;  /**<  array of items                  */
};

    /*
     *  Function prototypes for all declared enums, structs and unions
     */

  /*
   *  Utility functions for enum attribute_visibility
   */

attribute_visibility attribute_attribute_visibility_from_str(char *enum_name);
char *attribute_attribute_visibility_to_str(attribute_visibility type);

  /*
   *  Utility functions for struct attribute
   */

attribute *attribute_new(void);
attribute *attribute_dup(attribute *instance);
void attribute_free(attribute *instance);
char *attribute_get_name(attribute *instance);
void attribute_set_name(attribute *instance, char *name);
char *attribute_get_value(attribute *instance);
void attribute_set_value(attribute *instance, char *value);
attribute_visibility attribute_get_visibility(attribute *instance);
void attribute_set_visibility(attribute *instance,
                              attribute_visibility visibility);
char *attribute_visibility_to_string(attribute_visibility av);
attribute_visibility attribute_visibility_from_string(char *s);

  /*
   *  Utility functions for struct attribute_array
   */

attribute_array *attribute_array_new(void);
attribute_array *attribute_array_dup(attribute_array *instance);
void attribute_array_free(attribute_array *instance);
int attribute_array_get_current(attribute_array *instance);
void attribute_array_add(attribute_array *instance, attribute *item);
void attribute_array_remove(attribute_array *instance, int index);
attribute *attribute_array_first(attribute_array *instance);
attribute *attribute_array_next(attribute_array *instance);
attribute *attribute_array_previous(attribute_array *instance);
attribute *attribute_array_last(attribute_array *instance);
attribute *attribute_array_current(attribute_array *instance);

#endif //ATTRIBUTE_H
