/*
 *  Copyright 2026 - Patrick Head
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 *  @file attribute.c
 *  @brief functions to manage attribute data
 *
 *  This file was generated by kahdifire
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include "attribute.h"

    /*
     *  Utility functions for enum attribute_visibility
     */

  /**
   *  @fn attribute_visibility attribute_attribute_visibility_from_str(char *enum_name)
   *  @brief converts @p enum_name to @a attribute_visibility value
   *
   *  @param enum_name - string version of @a attribute_visibility value
   *
   *  @return @a attribute_visibility value
   */

attribute_visibility attribute_attribute_visibility_from_str(char *enum_name)
{
  if (!enum_name) return 0;

  if (!strcmp(enum_name, "attribute_visibility_value")) return attribute_visibility_value;
  else if (!strcmp(enum_name, "attribute_visibility_both")) return attribute_visibility_both;
  else if (!strcmp(enum_name, "attribute_visibility_none")) return attribute_visibility_none;

  return 0;
}

  /**
   *  @fn char *attribute_attribute_visibility_to_str(attribute_visibility type)
   *  @brief converts @p type to string value
   *
   *  @param type - attribute_visibility value
   *
   *  @return string version of attribute_visibility value
   */

char *attribute_attribute_visibility_to_str(attribute_visibility type)
{
  switch (type)
  {
    case attribute_visibility_value: return "attribute_visibility_value";
    case attribute_visibility_both: return "attribute_visibility_both";
    case attribute_visibility_none: return "attribute_visibility_none";
  }

  return "UNKNOWN";
}

    /*
     *  Utility functions for struct attribute
     */

  /**
   *  @fn attribute *attribute_new(void)
   *  @brief creates a new @a struct @a attribute
   *
   *  @par Parameters
   *    None.
   *
   *  @return pointer to new @a struct @a attribute on success, NULL on failure
   */

attribute *attribute_new(void)
{
  attribute *instance = NULL;

  instance = malloc(sizeof(attribute));
  if (instance) memset(instance, 0, sizeof(attribute));

  return instance;
}

  /**
   *  @fn attribute *attribute_dup(attribute *instance)
   *  @brief creates a deep copy of @p instance
   *
   *  @param instance - pointer to @a struct @a attribute
   *
   *  @return pointer to new @a struct @a attribute on success, NULL on failure
   */

attribute *attribute_dup(attribute *instance)
{
  attribute *new_instance = NULL;

  if (!instance) goto exit;

  new_instance = attribute_new();
  if (!new_instance) goto exit;

  memcpy(new_instance, instance, sizeof(attribute));

  if (instance->name)
    new_instance->name = strdup(instance->name);

  if (instance->value)
    new_instance->value = strdup(instance->value);

exit:
  return new_instance;
}

  /**
   *  @fn void attribute_free(attribute *instance)
   *  @brief frees all memory allocated to @p instance
   *
   *  @param instance - pointer to @a struct @a attribute
   *
   *  Returns
   *    Nothing.
   */

void attribute_free(attribute *instance)
{
  if (!instance) goto exit;

  if (instance->name)
    free(instance->name);

  if (instance->value)
    free(instance->value);

  free(instance);

exit:
}

  /**
   *  @fn char *attribute_get_name(attribute *instance)
   *  @brief returns value of instance->name
   *
   *  @param instance - pointer to @a attribute
   *
   *  @return char* on success, 0 or NULL on failure
   */

char *attribute_get_name(attribute *instance)
{
  return instance ? instance->name : NULL;
}

  /**
   *  @fn void attribute_set_name(attribute *instance, char *name)
   *  @brief sets value of instance->name
   *
   *  @param instance - pointer to @a attribute
   *  @param name - new value
   *
   *  @par Returns
   *    Nothing.
   */

void attribute_set_name(attribute *instance, char *name)
{
  if (!instance) return;

  if (instance->name) free(instance->name);
  instance->name = NULL;
  if (name) instance->name = strdup(name);
}

  /**
   *  @fn char *attribute_get_value(attribute *instance)
   *  @brief returns value of instance->value
   *
   *  @param instance - pointer to @a attribute
   *
   *  @return char* on success, 0 or NULL on failure
   */

char *attribute_get_value(attribute *instance)
{
  return instance ? instance->value : NULL;
}

  /**
   *  @fn void attribute_set_value(attribute *instance, char *value)
   *  @brief sets value of instance->value
   *
   *  @param instance - pointer to @a attribute
   *  @param value - new value
   *
   *  @par Returns
   *    Nothing.
   */

void attribute_set_value(attribute *instance, char *value)
{
  if (!instance) return;

  if (instance->value) free(instance->value);
  instance->value = NULL;
  if (value) instance->value = strdup(value);
}

  /**
   *  @fn char *attribute_get_visibility(attribute *instance)
   *  @brief returns value of instance->visibility
   *
   *  @param instance - pointer to @a attribute
   *
   *  @return attribute_visibility
   */

attribute_visibility attribute_get_visibility(attribute *instance)
{
  return instance ? instance->visibility : attribute_visibility_value;
}

  /**
   *  @fn void attribute_set_visibility(attribute *instance,
   *                                    attribute_visibility visibility)
   *  @brief sets value of instance->visibility
   *
   *  @param instance - pointer to @a attribute
   *  @param visibility - new @ attribute_visibility
   *
   *  @par Returns
   *    Nothing.
   */

void attribute_set_visibility(attribute *instance,
                              attribute_visibility visibility)
{
  if (!instance) return;

  instance->visibility = visibility;
}

  /**
   *  @fn char *attribute_visibility_to_string(attribute_visibility av)
   *  @brief convert @a attribute_visibility value to string
   *
   *  @param av - @a attribute_visibility value
   *
   *  @return pointer to string containing @a attribute_visibility equivalent
   */

char *attribute_visibility_to_string(attribute_visibility av)
{
  switch (av)
  {
    case attribute_visibility_value: return "value";
    case attribute_visibility_both: return "both";
    case attribute_visibility_none: return "none";

    default: return "value";
  }

  return "value";
}

  /**
   *  @fn attribute_visibility attribute_visibility_from_string(char *s)
   *  @brief convert string to @a attribute_visibility value
   *
   *  @param s - string representation of @a attribute_visibility
   *
   *  @return @a attribute_visibility value
   */

attribute_visibility attribute_visibility_from_string(char *s)
{
  attribute_visibility visibility = attribute_visibility_value;

  if (!s) goto exit;

  if (!strcmp(s, "value")) visibility = attribute_visibility_value;
  else if (!strcmp(s, "both")) visibility = attribute_visibility_both;
  else if (!strcmp(s, "none")) visibility = attribute_visibility_none;

exit:
  return visibility;
}

    /*
     *  Utility functions for struct attribute_array
     */

  /**
   *  @fn attribute_array *attribute_array_new(void)
   *  @brief creates a new @a attribute_array struct
   *
   *  @par Parameters
   *    None.
   *
   *  @return pointer to new @a attribute_array on success, NULL on failure
   */

attribute_array *attribute_array_new(void)
{
  attribute_array *instance = NULL;

  instance = malloc(sizeof(attribute_array));
  if (instance) memset(instance, 0, sizeof(attribute_array));

  return instance;
}

  /**
   *  @fn attribute_array *attribute_array_dup(attribute_array *instance)
   *  @brief creates a deep copy of @a attribute_array struct
   *
   *  @param instance - pointer to attribute_array struct
   *
   *  @return pointer to new @a attribute_array on success, NULL on failure
   */

attribute_array *attribute_array_dup(attribute_array *instance)
{
  attribute_array *new_instance = NULL;
  int i;

  if (!instance) goto exit;

  new_instance = attribute_array_new();
  if (!new_instance) goto exit;

  for (i = 0; i < instance->n; i++)
    attribute_array_add(new_instance, instance->item[i]);

exit:
  return new_instance;
}

  /**
   *  @fn void attribute_array_free(attribute_array *instance)
   *  @brief frees all memory allocated to @p instance
   *
   *  @param instance - pointer to @a attribute_array_array struct
   *
   *  Returns
   *    Nothing.
   */

void attribute_array_free(attribute_array *instance)
{
  int i;

  if (!instance) goto exit;

  for (i = 0; i < instance->n; i++)
    attribute_free(instance->item[i]);

  free(instance->item);
  free(instance);

exit:
}

  /**
   *  @fn int attribute_array_get_current(attribute_array *instance)
   *  @brief returns current index value of @p instance list
   *
   *  @param instance - pointer to @a attribute_array struct
   *
   *  @return current index value of @a attribute_array
   */

int attribute_array_get_current(attribute_array *instance)
{
  return instance ? instance->current : 0;
}

  /**
   *  @fn void attribute_array_add(attribute_array *instance, attribute *item)
   *  @brief adds @p item to @p instance list
   *
   *  @param instance - pointer to @a attribute_array struct
   *  @param item - pointer to @a attribute struct
   *
   *  @par Returns
   *  Nothing.
   */

void attribute_array_add(attribute_array *instance, attribute *item)
{
  void *tmp = NULL;

  if (!instance || !item) return;

  tmp = realloc(instance->item, sizeof(attribute *) * (instance->n + 1));
  if (!tmp) return;
  instance->item = tmp;

  instance->item[instance->n] = attribute_dup(item);

  ++instance->n;
}

  /**
   *  @fn void attribute_array_remove(attribute_array *instance, int index)
   *  @brief removes item at @p index from @p instance list
   *
   *  @param instance - pointer to @a attribute_array struct
   *  @param index - index into instance->item array
   *
   *  @par Returns
   *  Nothing.
   */

void attribute_array_remove(attribute_array *instance, int index)
{
  int i;
  void *tmp = NULL;

  if (!instance) return;
  if (index < 0) return;
  if (index >= instance->n) return;

  attribute_free(instance->item[index]);

  for (i = index; i < instance->n - 1; i++)
    instance->item[i] = instance->item[i + 1];

  --instance->n;

  tmp = realloc(instance->item, sizeof(attribute *) * instance->n);
  if (!tmp) return;

  instance->item = tmp;
}

  /**
   *  @fn attribute *attribute_array_first(attribute_array *instance)
   *  @brief returns first item in @a attribute_array
   *
   *  @param instance - pointer to @a attribute_array struct
   *
   *  @return pointer to @a attribute on success, NULL on failure
   */

attribute *attribute_array_first(attribute_array *instance)
{
  attribute *item = NULL;

  if (!instance) goto exit;
  if (!instance->n) goto exit;

  instance->current = 0;
  item = instance->item[0];

exit:
  return item;
}

  /**
   *  @fn attribute *attribute_array_next(attribute_array *instance)
   *  @brief returns next item in @a attribute_array
   *
   *  @param instance - pointer to @a attribute_array struct
   *
   *  @return pointer to @a attribute on success, NULL on failure
   */

attribute *attribute_array_next(attribute_array *instance)
{
  attribute *item = NULL;

  if (!instance) goto exit;
  if (!instance->n) goto exit;

  if (instance->current < 0) instance->current = 0;
  else if (instance->current >= instance->n) instance->current = instance->n - 1;

  ++instance->current;

  if (instance->current >= instance->n)
    instance->current = 0;
  else
    item = instance->item[instance->current];

exit:
  return item;
}

  /**
   *  @fn attribute *attribute_array_previous(attribute_array *instance)
   *  @brief returns previous item in @a attribute_array
   *
   *  @param instance - pointer to @a attribute_array struct
   *
   *  @return pointer to @a attribute on success, NULL on failure
   */

attribute *attribute_array_previous(attribute_array *instance)
{
  attribute *item = NULL;

  if (!instance) goto exit;
  if (!instance->n) goto exit;

  if (instance->current < 0) instance->current = 0;
  else if (instance->current >= instance->n) instance->current = instance->n - 1;

  --instance->current;

  if (instance->current < 0)
    instance->current = instance->n - 1;
  else
    item = instance->item[instance->current];

exit:
  return item;
}

  /**
   *  @fn attribute *attribute_array_last(attribute_array *instance)
   *  @brief returns last item in @a attribute_array
   *
   *  @param instance - pointer to @a attribute_array struct
   *
   *  @return pointer to @a attribute on success, NULL on failure
   */

attribute *attribute_array_last(attribute_array *instance)
{
  attribute *item = NULL;

  if (!instance) goto exit;
  if (!instance->n) goto exit;

  instance->current = instance->n - 1;
  item = instance->item[instance->current];

exit:
  return item;
}

  /**
   *  @fn attribute *attribute_array_current(attribute_array *instance)
   *  @brief returns current item in @a attribute_array
   *
   *  @param instance - pointer to @a attribute_array struct
   *
   *  @return pointer to @a attribute on success, NULL on failure
   */

attribute *attribute_array_current(attribute_array *instance)
{
  attribute *item = NULL;

  if (!instance) goto exit;
  if (!instance->n) goto exit;

  if (instance->current < 0) instance->current = 0;
  if (instance->current >= instance->n) instance->current = instance->n - 1;

  item = instance->item[instance->current];

exit:
  return item;
}

