/*
 *  Copyright 2026 - Patrick Head
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 *  @file pin.h
 *  @brief functions to manage pin related data
 *
 *  This file was generated by kahdifire
 */

#ifndef PIN_H
#define PIN_H

#include <stdbool.h>
#include <stdint.h>

    /*
     *  Typedefs for all declared enums, structs and unions
     */

  /**
   *  @typedef pin
   *  @brief creates a type for @a pin struct
   */

typedef struct pin pin;

  /**
   *  @typedef pin_array
   *  @brief creates a type for @a pin_array struct
   */

typedef struct pin_array pin_array;

    /*
     *  Declarations for all enums, structs and unions
     */

  /**
   *  @typedef enum pin_location
   *  @brief creates a type for enum @a pin_location and values
   */

typedef enum
{
  pin_location_right = 0,  /**< pins on right of shape */
  pin_location_left = 1,  /**< pins on left of shape */
  pin_location_top = 2,  /**< pins on top of shape */
  pin_location_bottom = 3  /**< pins on bottom of shape */
} pin_location;

  /**
   *  @typedef enum pin_direction
   *  @brief creates a type for enum @a pin_direction and values
   */

typedef enum
{
  pin_direction_none = 0,  /**< no special decoration */
  pin_direction_in = 1,  /**< input decoration */
  pin_direction_out = 2  /**< output decoration ANNOTATION */
} pin_direction;

  /**
   *  @struct pin
   *  @brief declares struct @a pin
   */

struct pin
{
  char *name; /**< name as supplied in 'begin pin' command */
  unsigned int num;  /**<  pin number on package  */
  pin_location location;  /**<  side of shape for pin */
  pin_direction direction;  /**<  input/output decoration */
  char *label;  /**<  Alternate label name for pin */
  bool inverted_circle;  /**<  inverted IO symbol */
  bool funcmap;  /**<  use func map to get pin name */
};

  /**
   *  @struct pin_array
   *  @brief struct used to manage a dynamic array of @a pin structs
   */

struct pin_array
{
  int n;          /**<  number of items in array         */
  int current;    /**<  index of current item in array   */
  pin **item;     /**<  array of items                  */
};

    /*
     *  Function prototypes for all declared enums, structs and unions
     */

  /*
   *  Utility functions for enum pin_location
   */

pin_location pin_pin_location_from_str(char *enum_name);
char *pin_pin_location_to_str(pin_location type);

  /*
   *  Utility functions for enum pin_direction
   */

pin_direction pin_pin_direction_from_str(char *enum_name);
char *pin_pin_direction_to_str(pin_direction type);

  /*
   *  Utility functions for struct pin
   */

pin *pin_new(void);
pin *pin_dup(pin *instance);
void pin_free(pin *instance);
char *pin_get_name(pin *instance);
void pin_set_name(pin *instance, char *name);
unsigned int pin_get_num(pin *instance);
void pin_set_num(pin *instance, unsigned int num);
pin_location pin_get_location(pin *instance);
void pin_set_location(pin *instance, pin_location location);
pin_direction pin_get_direction(pin *instance);
void pin_set_direction(pin *instance, pin_direction direction);
char *pin_get_label(pin *instance);
void pin_set_label(pin *instance, char *label);
bool pin_get_inverted_circle(pin *instance);
void pin_set_inverted_circle(pin *instance, bool inverted_circle);
bool pin_get_funcmap(pin *instance);
void pin_set_funcmap(pin *instance, bool funcmap);
char *pin_direction_to_string(pin_direction pd);
pin_direction pin_direction_from_string(char *s);
char *pin_location_to_string(pin_location pl);
pin_location pin_location_from_string(char *s);

  /*
   *  Utility functions for struct pin_array
   */

pin_array *pin_array_new(void);
pin_array *pin_array_dup(pin_array *instance);
void pin_array_free(pin_array *instance);
int pin_array_get_current(pin_array *instance);
void pin_array_add(pin_array *instance, pin *item);
void pin_array_remove(pin_array *instance, int index);
pin *pin_array_first(pin_array *instance);
pin *pin_array_next(pin_array *instance);
pin *pin_array_previous(pin_array *instance);
pin *pin_array_last(pin_array *instance);
pin *pin_array_current(pin_array *instance);

#endif //PIN_H
