/*
 *  Copyright 2026 - Patrick Head
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 *  @file pinalign.c
 *  @brief functions to manage pinalign data
 *
 *  This file was generated by kahdifire
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include "pinalign.h"

    /*
     *  Utility functions for enum pinalign_side
     */

  /**
   *  @fn pinalign_side pinalign_pinalign_side_from_str(char *enum_name)
   *  @brief converts @p enum_name to @a pinalign_side value
   *
   *  @param enum_name - string version of @a pinalign_side value
   *
   *  @return @a pinalign_side value
   */

pinalign_side pinalign_pinalign_side_from_str(char *enum_name)
{
  if (!enum_name) return 0;

  if (!strcmp(enum_name, "pinalign_side_right")) return pinalign_side_right;
  else if (!strcmp(enum_name, "pinalign_side_left")) return pinalign_side_left;
  else if (!strcmp(enum_name, "pinalign_side_top")) return pinalign_side_top;
  else if (!strcmp(enum_name, "pinalign_side_bottom")) return pinalign_side_bottom;

  return 0;
}

  /**
   *  @fn char *pinalign_pinalign_side_to_str(pinalign_side type)
   *  @brief converts @p type to string value
   *
   *  @param type - pinalign_side value
   *
   *  @return string version of pinalign_side value
   */

char *pinalign_pinalign_side_to_str(pinalign_side type)
{
  switch (type)
  {
    case pinalign_side_right: return "pinalign_side_right";
    case pinalign_side_left: return "pinalign_side_left";
    case pinalign_side_top: return "pinalign_side_top";
    case pinalign_side_bottom: return "pinalign_side_bottom";
  }

  return "UNKNOWN";
}

    /*
     *  Utility functions for enum pinalign_place
     */

  /**
   *  @fn pinalign_place pinalign_pinalign_place_from_str(char *enum_name)
   *  @brief converts @p enum_name to @a pinalign_place value
   *
   *  @param enum_name - string version of @a pinalign_place value
   *
   *  @return @a pinalign_place value
   */

pinalign_place pinalign_pinalign_place_from_str(char *enum_name)
{
  if (!enum_name) return 0;

  if (!strcmp(enum_name, "pinalign_place_start")) return pinalign_place_start;
  else if (!strcmp(enum_name, "pinalign_place_center")) return pinalign_place_center;

  return 0;
}

  /**
   *  @fn char *pinalign_pinalign_place_to_str(pinalign_place type)
   *  @brief converts @p type to string value
   *
   *  @param type - pinalign_place value
   *
   *  @return string version of pinalign_place value
   */

char *pinalign_pinalign_place_to_str(pinalign_place type)
{
  switch (type)
  {
    case pinalign_place_start: return "pinalign_place_start";
    case pinalign_place_center: return "pinalign_place_center";
  }

  return "UNKNOWN";
}

    /*
     *  Utility functions for struct pinalign
     */

  /**
   *  @fn pinalign *pinalign_new(void)
   *  @brief creates a new @a struct @a pinalign
   *
   *  @par Parameters
   *    None.
   *
   *  @return pointer to new @a struct @a pinalign on success, NULL on failure
   */

pinalign *pinalign_new(void)
{
  pinalign *instance = NULL;

  instance = malloc(sizeof(pinalign));
  if (instance) memset(instance, 0, sizeof(pinalign));

  return instance;
}

  /**
   *  @fn pinalign *pinalign_dup(pinalign *instance)
   *  @brief creates a deep copy of @p instance
   *
   *  @param instance - pointer to @a struct @a pinalign
   *
   *  @return pointer to new @a struct @a pinalign on success, NULL on failure
   */

pinalign *pinalign_dup(pinalign *instance)
{
  pinalign *new_instance = NULL;

  if (!instance) goto exit;

  new_instance = pinalign_new();
  if (!new_instance) goto exit;

  memcpy(new_instance, instance, sizeof(pinalign));

exit:
  return new_instance;
}

  /**
   *  @fn void pinalign_free(pinalign *instance)
   *  @brief frees all memory allocated to @p instance
   *
   *  @param instance - pointer to @a struct @a pinalign
   *
   *  Returns
   *    Nothing.
   */

void pinalign_free(pinalign *instance)
{
  if (!instance) goto exit;

  free(instance);

exit:
}

  /**
   *  @fn char *pinalign_get_side(pinalign *instance)
   *  @brief returns value of instance->side
   *
   *  @param instance - pointer to @a pinalign
   *
   *  @return pinalign_side
   */

pinalign_side pinalign_get_side(pinalign *instance)
{
  return instance ? instance->side : pinalign_side_right;
}

  /**
   *  @fn void pinalign_set_side(pinalign *instance, pinalign_side side)
   *  @brief sets value of instance->side
   *
   *  @param instance - pointer to @a pinalign
   *  @param side - new @ pinalign_side
   *
   *  @par Returns
   *    Nothing.
   */

void pinalign_set_side(pinalign *instance, pinalign_side side)
{
  if (!instance) return;

  instance->side = side;
}

  /**
   *  @fn char *pinalign_get_place(pinalign *instance)
   *  @brief returns value of instance->place
   *
   *  @param instance - pointer to @a pinalign
   *
   *  @return pinalign_place
   */

pinalign_place pinalign_get_place(pinalign *instance)
{
  return instance ? instance->place : pinalign_place_start;
}

  /**
   *  @fn void pinalign_set_place(pinalign *instance, pinalign_place place)
   *  @brief sets value of instance->place
   *
   *  @param instance - pointer to @a pinalign
   *  @param place - new @ pinalign_place
   *
   *  @par Returns
   *    Nothing.
   */

void pinalign_set_place(pinalign *instance, pinalign_place place)
{
  if (!instance) return;

  instance->place = place;
}

  /**
   *  @fn char *pinalign_side_to_string(pinalign_side pas)
   *  @brief converts @a pinalign_side value to a string
   *
   *  @param pas - @ pinalign_side value
   *
   *  @return string containing equivalent @ pinalign_side value
   */

char *pinalign_side_to_string(pinalign_side pas)
{
  switch (pas)
  {
    case pinalign_side_right: return "right";
    case pinalign_side_left: return "left";
    case pinalign_side_top: return "top";
    case pinalign_side_bottom: return "bottom";

    default: return "right";
  }

  return "right";
}

  /**
   *  @fn pinalign_side pinalign_side_from_string(char *s)
   *  @brief converts string to @a pinalign_side value
   *
   *  @param s - string representation of @a pinalign_side value
   *
   *  @return @a pinalign_side value
   */

pinalign_side pinalign_side_from_string(char *s)
{
  pinalign_side side = pinalign_side_right;

  if (!s) goto exit;

  if (!strcmp(s, "right")) side = pinalign_side_right;
  else if (!strcmp(s, "left")) side = pinalign_side_left;
  else if (!strcmp(s, "top")) side = pinalign_side_top;
  else if (!strcmp(s, "bottom")) side = pinalign_side_bottom;

exit:
  return side;
}

  /**
   *  @fn char *pinalign_place_to_string(pinalign_place pap)
   *  @brief converts @a pinalign_place value to a string
   *
   *  @param pas - @ pinalign_place value
   *
   *  @return string containing equivalent @ pinalign_place value
   */

char *pinalign_place_to_string(pinalign_place pap)
{
  switch (pap)
  {
    case pinalign_place_start: return "start";
    case pinalign_place_center: return "center";

    default: return "start";
  }

  return "start";
}

  /**
   *  @fn pinalign_place pinalign_place_from_string(char *s)
   *  @brief converts string to @a pinalign_place value
   *
   *  @param s - string representation of @a pinalign_place value
   *
   *  @return @a pinalign_place value
   */

pinalign_place pinalign_place_from_string(char *s)
{
  pinalign_place place = pinalign_place_start;

  if (!s) goto exit;

  if (!strcmp(s, "start")) place = pinalign_place_start;
  else if (!strcmp(s, "center")) place = pinalign_place_center;

exit:
  return place;
}

