/*
 *  Copyright 2026 - Patrick Head
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 *  @file shape.h
 *  @brief functions to manage shape data
 *
 *  This file was generated by kahdifire
 */

#ifndef SHAPE_H
#define SHAPE_H

#include <stdbool.h>
#include <stdint.h>

    /*
     *  Typedefs for all declared enums, structs and unions
     */

  /**
   *  @typedef shape
   *  @brief creates a type for @a shape struct
   */

typedef struct shape shape;

  /**
   *  @typedef shape_array
   *  @brief creates a type for @a shape_array struct
   */

typedef struct shape_array shape_array;

    /*
     *  Declarations for all enums, structs and unions
     */

  /**
   *  @typedef enum shape_type
   *  @brief creates a type for enum @a shape_type and values
   */

typedef enum
{
  shape_type_none = 0,  /**< no shape specificied */
  shape_type_box = 1  /**< a box shape */
} shape_type;

  /**
   *  @struct shape
   *  @brief declares struct @a shape
   */

struct shape
{
  shape_type type;  /**<  which shape to use */
  bool filled;  /**<  is shape filled */
};

  /**
   *  @struct shape_array
   *  @brief struct used to manage a dynamic array of @a shape structs
   */

struct shape_array
{
  int n;          /**<  number of items in array         */
  int current;    /**<  index of current item in array   */
  shape **item;   /**<  array of items                  */
};

    /*
     *  Function prototypes for all declared enums, structs and unions
     */

  /*
   *  Utility functions for enum shape_type
   */

shape_type shape_shape_type_from_str(char *enum_name);
char *shape_shape_type_to_str(shape_type type);

  /*
   *  Utility functions for struct shape
   */

shape *shape_new(void);
shape *shape_dup(shape *instance);
void shape_free(shape *instance);
shape_type shape_get_type(shape *instance);
void shape_set_type(shape *instance, shape_type type);
bool shape_get_filled(shape *instance);
void shape_set_filled(shape *instance, bool filled);
char *shape_type_to_string(shape_type st);
shape_type shape_type_from_string(char *s);

  /*
   *  Utility functions for struct shape_array
   */

shape_array *shape_array_new(void);
shape_array *shape_array_dup(shape_array *instance);
void shape_array_free(shape_array *instance);
int shape_array_get_current(shape_array *instance);
void shape_array_add(shape_array *instance, shape *item);
void shape_array_remove(shape_array *instance, int index);
shape *shape_array_first(shape_array *instance);
shape *shape_array_next(shape_array *instance);
shape *shape_array_previous(shape_array *instance);
shape *shape_array_last(shape_array *instance);
shape *shape_array_current(shape_array *instance);

#endif //SHAPE_H
