/*
 *  Copyright 2026 - Patrick Head
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 *  @file slot.h
 *  @brief functions to manage slot data
 *
 *  This file was generated by kahdifire
 */

#ifndef SLOT_H
#define SLOT_H

#include <stdbool.h>
#include <stdint.h>

#include "shape.h"
#include "pinalign.h"
#include "attribute.h"
#include "pin.h"

    /*
     *  Typedefs for all declared enums, structs and unions
     */

  /**
   *  @typedef slot
   *  @brief creates a type for @a slot struct
   */

typedef struct slot slot;

  /**
   *  @typedef slot_array
   *  @brief creates a type for @a slot_array struct
   */

typedef struct slot_array slot_array;

    /*
     *  Declarations for all enums, structs and unions
     */

  /**
   *  @struct slot
   *  @brief declares struct @a slot
   */

struct slot
{
  char *name;  /**< name of slot */
  shape shape;  /**<  shape of slot decoration */
  pinalign pinalignment[4];  /**<  pin alignment for each side of slot */
  char *label;  /**<  label for slot */
  attribute_array *attributes;  /**<  any attributes attached to slot */
  pin_array *pins;  /**< list of pins associated with this slot */
  unsigned int width;  /**< width of "box" (using standard 4000 grid) */
  unsigned int height;  /**< height of "box" (using standard 4000 grid) */
};

  /**
   *  @struct slot_array
   *  @brief struct used to manage a dynamic array of @a slot structs
   */

struct slot_array
{
  int n;          /**<  number of items in array         */
  int current;    /**<  index of current item in array   */
  slot **item;    /**<  array of items                  */
};

    /*
     *  Function prototypes for all declared enums, structs and unions
     */

  /*
   *  Utility functions for struct slot
   */

slot *slot_new(void);
slot *slot_dup(slot *instance);
void slot_free(slot *instance);
char *slot_get_name(slot *instance);
void slot_set_name(slot *instance, char *name);
shape *slot_get_shape(slot *instance);
void slot_set_shape(slot *instance, shape *new_shape);
pinalign *slot_get_pinalignment(slot *instance, pinalign_side side);
void slot_set_pinalignment(slot *instance, pinalign *pinalignment);
char *slot_get_label(slot *instance);
void slot_set_label(slot *instance, char *label);
attribute_array *slot_get_attributes(slot *instance);
void slot_set_attributes(slot *instance, attribute_array *attributes);
pin_array *slot_get_pins(slot *instance);
void slot_set_pins(slot *instance, pin_array *pins);
int slot_get_width(slot *instance);
void slot_set_width(slot *instance, unsigned int width);
int slot_get_height(slot *instance);
void slot_set_height(slot *instance, unsigned int height);

  /*
   *  Utility functions for struct slot_array
   */

slot_array *slot_array_new(void);
slot_array *slot_array_dup(slot_array *instance);
void slot_array_free(slot_array *instance);
slot *slot_array_get(slot_array *instance, unsigned int idx);
int slot_array_get_current(slot_array *instance);
void slot_array_add(slot_array *instance, slot *item);
void slot_array_remove(slot_array *instance, int index);
slot *slot_array_first(slot_array *instance);
slot *slot_array_next(slot_array *instance);
slot *slot_array_previous(slot_array *instance);
slot *slot_array_last(slot_array *instance);
slot *slot_array_current(slot_array *instance);

#endif //SLOT_H
