/*
 *  Copyright 2026 - Patrick Head
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 *  @file symbol.c
 *  @brief functions to manage a symbol struct - brief
 *
 *  This file was generated by kahdifire
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include "symbol.h"

    /*
     *  Utility functions for struct symbol
     */

  /**
   *  @fn symbol *symbol_new(void)
   *  @brief creates a new @a struct @a symbol
   *
   *  @par Parameters
   *    None.
   *
   *  @return pointer to new @a struct @a symbol on success, NULL on failure
   */

symbol *symbol_new(void)
{
  symbol *instance = NULL;

  instance = malloc(sizeof(symbol));
  if (instance) memset(instance, 0, sizeof(symbol));

  instance->slots = slot_array_new();

  return instance;
}

  /**
   *  @fn symbol *symbol_dup(symbol *instance)
   *  @brief creates a deep copy of @p instance
   *
   *  @param instance - pointer to @a struct @a symbol
   *
   *  @return pointer to new @a struct @a symbol on success, NULL on failure
   */

symbol *symbol_dup(symbol *instance)
{
  symbol *new_instance = NULL;

  if (!instance) goto exit;

  new_instance = symbol_new();
  if (!new_instance) goto exit;

  memcpy(new_instance, instance, sizeof(symbol));

  if (instance->refdes)
    new_instance->refdes = strdup(instance->refdes);

  new_instance->slots = slot_array_dup(instance->slots);

exit:
  return new_instance;
}

  /**
   *  @fn void symbol_free(symbol *instance)
   *  @brief frees all memory allocated to @p instance
   *
   *  @param instance - pointer to @a struct @a symbol
   *
   *  Returns
   *    Nothing.
   */

void symbol_free(symbol *instance)
{
  if (!instance) goto exit;

  if (instance->refdes)
    free(instance->refdes);

  if (instance->slots) slot_array_free(instance->slots);

  free(instance);

exit:
}

  /**
   *  @fn char *symbol_get_refdes(symbol *instance)
   *  @brief returns value of instance->refdes
   *
   *  @param instance - pointer to @a symbol
   *
   *  @return char* on success, 0 or NULL on failure
   */

char *symbol_get_refdes(symbol *instance)
{
  return instance ? instance->refdes : NULL;
}

  /**
   *  @fn void symbol_set_refdes(symbol *instance, char *refdes)
   *  @brief sets value of instance->refdes
   *
   *  @param instance - pointer to @a symbol
   *  @param refdes - new value
   *
   *  @par Returns
   *    Nothing.
   */

void symbol_set_refdes(symbol *instance, char *refdes)
{
  if (!instance) return;

  if (instance->refdes) free(instance->refdes);
  instance->refdes = NULL;
  if (refdes) instance->refdes = strdup(refdes);
}

  /**
   *  @fn double symbol_get_text_size_mult(symbol *instance)
   *  @brief returns value of instance->text_size_mult
   *
   *  @param instance - pointer to @a symbol
   *
   *  @return double on success, 0 or NULL on failure
   */

double symbol_get_text_size_mult(symbol *instance)
{
  return instance ? instance->text_size_mult : 0;
}

  /**
   *  @fn void symbol_set_text_size_mult(symbol *instance, double text_size_mult)
   *  @brief sets value of instance->text_size_mult
   *
   *  @param instance - pointer to @a symbol
   *  @param text_size_mult - new value
   *
   *  @par Returns
   *    Nothing.
   */

void symbol_set_text_size_mult(symbol *instance, double text_size_mult)
{
  if (!instance) return;

  if (instance) instance->text_size_mult = text_size_mult;
}

  /**
   *  @fn char *symbol_get_slots(symbol *instance)
   *  @brief returns value of instance->slots
   *
   *  @param instance - pointer to @a symbol
   *
   *  @return slot_array * on success, 0 or NULL on failure
   */

slot_array *symbol_get_slots(symbol *instance)
{
  return instance ? instance->slots : NULL;
}

  /**
   *  @fn void symbol_set_slots(symbol *instance,
   *                            slot_array *slots)
   *  @brief sets value of instance->slots
   *
   *  @param instance - pointer to @a symbol
   *  @param slots - new value
   *
   *  @par Returns
   *    Nothing.
   */

void symbol_set_slots(symbol *instance, slot_array *slots)
{
  if (!instance) return;

  if (instance->slots) slot_array_free(instance->slots);
  instance->slots = NULL;
  if (slots) instance->slots = slot_array_dup(slots);
}

  /**
   *  @fn slot *symbol_find_slot(symbol *instance, char *name)
   *  @brief finds a slot in a list of slots by @p name
   *
   *  @param instance - pointer to @a symbol
   *  @param name - string containing name to find
   *
   *  @return slot * on success, 0 or NULL on failure
   */

slot *symbol_find_slot(symbol *instance, char *name)
{
  slot *sl = NULL;

  if (!instance || !name) goto exit;

  for (sl = slot_array_first(instance->slots);
       sl;
       sl = slot_array_next(instance->slots))
  {
    if (!strcmp(sl->name, name)) break;
  }

exit:
  return sl;
}

