/*
 *  Copyright 2026 - Patrick Head
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 *  @file pinalign.h
 *  @brief functions to manage pinalign data
 *
 *  This file was generated by kahdifire
 */

#ifndef PINALIGN_H
#define PINALIGN_H

#include <stdbool.h>
#include <stdint.h>

    /*
     *  Typedefs for all declared enums, structs and unions
     */

  /**
   *  @typedef pinalign
   *  @brief creates a type for @a pinalign struct
   */

typedef struct pinalign pinalign;

    /*
     *  Declarations for all enums, structs and unions
     */

  /**
   *  @typedef enum pinalign_side
   *  @brief creates a type for enum @a pinalign_side and values
   */

typedef enum
{
  pinalign_side_right = 0,  /**< setting for right side pins */
  pinalign_side_left = 1,  /**< setting for left side pins */
  pinalign_side_top = 2,  /**< setting for top side pins */
  pinalign_side_bottom = 3  /**< setting for bottom side pins */
} pinalign_side;

  /**
   *  @typedef enum pinalign_place
   *  @brief creates a type for enum @a pinalign_place and values
   */

typedef enum
{
  pinalign_place_start = 0,  /**< pin placement from start of side */
  pinalign_place_center = 1  /**< pin placement from center of side */
} pinalign_place;

  /**
   *  @struct pinalign
   *  @brief declares struct @a pinalign
   */

struct pinalign
{
  pinalign_side side;  /**<  setting is for this side */
  pinalign_place place;  /**<  pin placement setting */
};

    /*
     *  Function prototypes for all declared enums, structs and unions
     */

  /*
   *  Utility functions for enum pinalign_side
   */

pinalign_side pinalign_pinalign_side_from_str(char *enum_name);
char *pinalign_pinalign_side_to_str(pinalign_side type);

  /*
   *  Utility functions for enum pinalign_place
   */

pinalign_place pinalign_pinalign_place_from_str(char *enum_name);
char *pinalign_pinalign_place_to_str(pinalign_place type);

  /*
   *  Utility functions for struct pinalign
   */

pinalign *pinalign_new(void);
pinalign *pinalign_dup(pinalign *instance);
void pinalign_free(pinalign *instance);
pinalign_side pinalign_get_side(pinalign *instance);
void pinalign_set_side(pinalign *instance, pinalign_side side);
pinalign_place pinalign_get_place(pinalign *instance);
void pinalign_set_place(pinalign *instance, pinalign_place place);
char *pinalign_side_to_string(pinalign_side pas);
pinalign_side pinalign_side_from_string(char *s);
char *pinalign_place_to_string(pinalign_place pap);
pinalign_place pinalign_place_from_string(char *s);

#endif //PINALIGN_H
