/*
 *  Copyright 2026 - Patrick Head
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 *  @file symbol.h
 *  @brief functions to manage a symbol struct - brief
 *
 *  This file was generated by kahdifire
 */

#ifndef SYMBOL_H
#define SYMBOL_H

#include <stdbool.h>
#include <stdint.h>

#include "attribute.h"
#include "slot.h"

    /*
     *  Typedefs for all declared enums, structs and unions
     */

  /**
   *  @typedef symbol
   *  @brief creates a type for @a symbol struct
   */

typedef struct symbol symbol;

    /*
     *  Declarations for all enums, structs and unions
     */

  /**
   *  @struct symbol
   *  @brief declares struct @a symbol
   */

struct symbol
{
  char *refdes;  /**<  Required and only once, symbol ID in schematic */
  double text_size_mult;  /**<  text size length multiplier factor */
  slot_array *slots;  /**<  all defined slots, slots[0] is implicit global */
};

    /*
     *  Function prototypes for all declared enums, structs and unions
     */

  /*
   *  Utility functions for struct symbol
   */

symbol *symbol_new(void);
symbol *symbol_dup(symbol *instance);
void symbol_free(symbol *instance);
char *symbol_get_refdes(symbol *instance);
void symbol_set_refdes(symbol *instance, char *refdes);
double symbol_get_text_size_mult(symbol *instance);
void symbol_set_text_size_mult(symbol *instance, double text_size_mult);
slot_array *symbol_get_slots(symbol *instance);
slot *symbol_find_slot(symbol *instance, char *name);
void symbol_set_slots(symbol *instance, struct slot_array *slots);

#endif //SYMBOL_H
