/*
 *  Copyright 2026 - Patrick Head
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 *  @file pin.c
 *  @brief functions to manage pin related data
 *
 *  This file was generated by kahdifire
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include "pin.h"

    /*
     *  Utility functions for enum pin_location
     */

  /**
   *  @fn pin_location pin_pin_location_from_str(char *enum_name)
   *  @brief converts @p enum_name to @a pin_location value
   *
   *  @param enum_name - string version of @a pin_location value
   *
   *  @return @a pin_location value
   */

pin_location pin_pin_location_from_str(char *enum_name)
{
  if (!enum_name) return 0;

  if (!strcmp(enum_name, "pin_location_right")) return pin_location_right;
  else if (!strcmp(enum_name, "pin_location_left")) return pin_location_left;
  else if (!strcmp(enum_name, "pin_location_top")) return pin_location_top;
  else if (!strcmp(enum_name, "pin_location_bottom")) return pin_location_bottom;

  return 0;
}

  /**
   *  @fn char *pin_pin_location_to_str(pin_location type)
   *  @brief converts @p type to string value
   *
   *  @param type - pin_location value
   *
   *  @return string version of pin_location value
   */

char *pin_pin_location_to_str(pin_location type)
{
  switch (type)
  {
    case pin_location_right: return "pin_location_right";
    case pin_location_left: return "pin_location_left";
    case pin_location_top: return "pin_location_top";
    case pin_location_bottom: return "pin_location_bottom";
  }

  return "UNKNOWN";
}

    /*
     *  Utility functions for enum pin_direction
     */

  /**
   *  @fn pin_direction pin_pin_direction_from_str(char *enum_name)
   *  @brief converts @p enum_name to @a pin_direction value
   *
   *  @param enum_name - string version of @a pin_direction value
   *
   *  @return @a pin_direction value
   */

pin_direction pin_pin_direction_from_str(char *enum_name)
{
  if (!enum_name) return 0;

  if (!strcmp(enum_name, "pin_direction_none")) return pin_direction_none;
  else if (!strcmp(enum_name, "pin_direction_in")) return pin_direction_in;
  else if (!strcmp(enum_name, "pin_direction_out")) return pin_direction_out;

  return 0;
}

  /**
   *  @fn char *pin_pin_direction_to_str(pin_direction type)
   *  @brief converts @p type to string value
   *
   *  @param type - pin_direction value
   *
   *  @return string version of pin_direction value
   */

char *pin_pin_direction_to_str(pin_direction type)
{
  switch (type)
  {
    case pin_direction_none: return "pin_direction_none";
    case pin_direction_in: return "pin_direction_in";
    case pin_direction_out: return "pin_direction_out";
  }

  return "UNKNOWN";
}

    /*
     *  Utility functions for struct pin
     */

  /**
   *  @fn pin *pin_new(void)
   *  @brief creates a new @a struct @a pin
   *
   *  @par Parameters
   *    None.
   *
   *  @return pointer to new @a struct @a pin on success, NULL on failure
   */

pin *pin_new(void)
{
  pin *instance = NULL;

  instance = malloc(sizeof(pin));
  if (instance) memset(instance, 0, sizeof(pin));

  return instance;
}

  /**
   *  @fn pin *pin_dup(pin *instance)
   *  @brief creates a deep copy of @p instance
   *
   *  @param instance - pointer to @a struct @a pin
   *
   *  @return pointer to new @a struct @a pin on success, NULL on failure
   */

pin *pin_dup(pin *instance)
{
  pin *new_instance = NULL;

  if (!instance) goto exit;

  new_instance = pin_new();
  if (!new_instance) goto exit;

  memcpy(new_instance, instance, sizeof(pin));

  if (instance->label)
    new_instance->label = strdup(instance->label);

exit:
  return new_instance;
}

  /**
   *  @fn void pin_free(pin *instance)
   *  @brief frees all memory allocated to @p instance
   *
   *  @param instance - pointer to @a struct @a pin
   *
   *  Returns
   *    Nothing.
   */

void pin_free(pin *instance)
{
  if (!instance) goto exit;

  if (instance->label)
    free(instance->label);

  free(instance);

exit:
}

  /**
   *  @fn char *pin_get_name(pin *instance)
   *  @brief returns value of instance->name
   *
   *  @param instance - pointer to @a pin
   *
   *  @return pointer to @a name string on success, NULL on failure
   */

char *pin_get_name(pin *instance)
{
  return instance ? instance->name : NULL;
}

  /**
   *  @fn void pin_set_name(pin *instance, char *name)
   *  @brief sets value of instance->name
   *
   *  @param instance - pointer to @a pin
   *  @param name - new value
   *
   *  @par Returns
   *    Nothing.
   */

void pin_set_name(pin *instance, char *name)
{
  if (!instance) return;

  if (instance->name) free(instance->name);
  instance->name = NULL;
  if (name) instance->name = strdup(name);
}

  /**
   *  @fn unsigned int pin_get_num(pin *instance)
   *  @brief returns value of instance->num
   *
   *  @param instance - pointer to @a pin
   *
   *  @return unsigned int on success, 0 or NULL on failure
   */

unsigned int pin_get_num(pin *instance)
{
  return instance ? instance->num : 0;
}

  /**
   *  @fn void pin_set_num(pin *instance, unsigned int num)
   *  @brief sets value of instance->num
   *
   *  @param instance - pointer to @a pin
   *  @param num - new value
   *
   *  @par Returns
   *    Nothing.
   */

void pin_set_num(pin *instance, unsigned int num)
{
  if (!instance) return;

  if (instance) instance->num = num;
}

  /**
   *  @fn pin_location pin_get_location(pin *instance)
   *  @brief returns value of instance->location
   *
   *  @param instance - pointer to @a pin
   *
   *  @return pin_location
   */

pin_location pin_get_location(pin *instance)
{
  return instance ? instance->location : pin_location_right;
}

  /**
   *  @fn void pin_set_location(pin *instance, pin_location location)
   *  @brief sets value of instance->location
   *
   *  @param instance - pointer to @a pin
   *  @param location - new pin_location
   *
   *  @par Returns
   *    Nothing.
   */

void pin_set_location(pin *instance, pin_location location)
{
  if (!instance) return;

  if (instance) instance->location = location;
}

  /**
   *  @fn pin_direction pin_get_direction(pin *instance)
   *  @brief returns value of instance->direction
   *
   *  @param instance - pointer to @a pin
   *
   *  @return pin_direction
   */

pin_direction pin_get_direction(pin *instance)
{
  return instance ? instance->direction : pin_direction_none;
}

  /**
   *  @fn void pin_set_direction(pin *instance, pin_direction direction)
   *  @brief sets value of instance->direction
   *
   *  @param instance - pointer to @a pin
   *  @param direction - new pin_direction
   *
   *  @par Returns
   *    Nothing.
   */

void pin_set_direction(pin *instance, pin_direction direction)
{
  if (!instance) return;

  if (instance) instance->direction = direction;
}

  /**
   *  @fn char *pin_get_label(pin *instance)
   *  @brief returns value of instance->label
   *
   *  @param instance - pointer to @a pin
   *
   *  @return char* on success, 0 or NULL on failure
   */

char *pin_get_label(pin *instance)
{
  return instance ? instance->label : NULL;
}

  /**
   *  @fn void pin_set_label(pin *instance, char *label)
   *  @brief sets value of instance->label
   *
   *  @param instance - pointer to @a pin
   *  @param label - new value
   *
   *  @par Returns
   *    Nothing.
   */

void pin_set_label(pin *instance, char *label)
{
  if (!instance) return;

  if (instance->label) free(instance->label);
  instance->label = NULL;
  if (label) instance->label = strdup(label);
}

  /**
   *  @fn bool pin_get_inverted_circle(pin *instance)
   *  @brief returns value of instance->inverted_circle
   *
   *  @param instance - pointer to @a pin
   *
   *  @return bool on success, 0 or NULL on failure
   */

bool pin_get_inverted_circle(pin *instance)
{
  return instance ? instance->inverted_circle : 0;
}

  /**
   *  @fn void pin_set_inverted_circle(pin *instance, bool inverted_circle)
   *  @brief sets value of instance->inverted_circle
   *
   *  @param instance - pointer to @a pin
   *  @param inverted_circle - new value
   *
   *  @par Returns
   *    Nothing.
   */

void pin_set_inverted_circle(pin *instance, bool inverted_circle)
{
  if (!instance) return;

  if (instance) instance->inverted_circle = inverted_circle;
}

  /**
   *  @fn bool pin_get_funcmap(pin *instance)
   *  @brief returns value of instance->funcmap
   *
   *  @param instance - pointer to @a pin
   *
   *  @return bool on success, 0 or NULL on failure
   */

bool pin_get_funcmap(pin *instance)
{
  return instance ? instance->funcmap : 0;
}

  /**
   *  @fn void pin_set_funcmap(pin *instance, bool funcmap)
   *  @brief sets value of instance->funcmap
   *
   *  @param instance - pointer to @a pin
   *  @param funcmap - new value
   *
   *  @par Returns
   *    Nothing.
   */

void pin_set_funcmap(pin *instance, bool funcmap)
{
  if (!instance) return;

  if (instance) instance->funcmap = funcmap;
}

  /**
   *  @fn char *pin_direction_to_string(pin_direction pd)
   *  @brief convert @a pin_direction value to string
   *
   *  @param pd - @a pin_direction value
   *
   *  @return string representation of @a pin_direction value
   */

char *pin_direction_to_string(pin_direction pd)
{
  switch (pd)
  {
    case pin_direction_none: return "NONE";
    case pin_direction_in: return "IN";
    case pin_direction_out: return "OUT";

    default: return "NONE";
  }

  return "NONE";
}

  /**
   *  @fn pin_direction pin_direction_from_string(char *s)
   *  @brief convert string to @a pin_location value
   *
   *  @param s - string representation of @a pin_direction value
   *
   *  @return @a pin_direction value
   */

pin_direction pin_direction_from_string(char *s)
{
  pin_direction dir = pin_direction_none;

  if (!s) goto exit;

  if (!strcmp(s, "in"))
    dir = pin_direction_in;
  else if (!strcmp(s, "out"))
    dir = pin_direction_out;
  else if (!strcmp(s, "none"))
    dir = pin_direction_none;

exit:
  return dir;
}

  /**
   *  @fn char *pin_location_to_string(pin_location pl)
   *  @brief convert @a pin_location value to string
   *
   *  @param pl - @a pin_location value
   *
   *  @return string representation of @a pin_location value
   */

char *pin_location_to_string(pin_location pl)
{
  switch (pl)
  {
    case pin_location_right: return "RIGHT";
    case pin_location_left: return "LEFT";
    case pin_location_top: return "TOP";
    case pin_location_bottom: return "BOTTOM";

    default: return "RIGHT";
  }

  return "RIGHT";
}

  /**
   *  @fn pin_location pin_location_from_string(char *s)
   *  @brief convert string to @a pin_location value
   *
   *  @param s - string representation of @a pin_location value
   *
   *  @return @a pin_location value
   */

pin_location pin_location_from_string(char *s)
{
  pin_location loc = pin_location_right;

  if (!s) goto exit;

  if (!strcmp(s, "left"))
    loc = pin_location_left;
  else if (!strcmp(s, "right"))
    loc = pin_location_right;
  else if (!strcmp(s, "top"))
    loc = pin_location_top;
  else if (!strcmp(s, "bottom"))
    loc = pin_location_bottom;

exit:
  return loc;
}
    /*
     *  Utility functions for struct pin_array
     */

  /**
   *  @fn pin_array *pin_array_new(void)
   *  @brief creates a new @a pin_array struct
   *
   *  @par Parameters
   *    None.
   *
   *  @return pointer to new @a pin_array on success, NULL on failure
   */

pin_array *pin_array_new(void)
{
  pin_array *instance = NULL;

  instance = malloc(sizeof(pin_array));
  if (instance) memset(instance, 0, sizeof(pin_array));

  return instance;
}

  /**
   *  @fn pin_array *pin_array_dup(pin_array *instance)
   *  @brief creates a deep copy of @a pin_array struct
   *
   *  @param instance - pointer to pin_array struct
   *
   *  @return pointer to new @a pin_array on success, NULL on failure
   */

pin_array *pin_array_dup(pin_array *instance)
{
  pin_array *new_instance = NULL;
  int i;

  if (!instance) goto exit;

  new_instance = pin_array_new();
  if (!new_instance) goto exit;

  for (i = 0; i < instance->n; i++)
    pin_array_add(new_instance, instance->item[i]);

exit:
  return new_instance;
}

  /**
   *  @fn void pin_array_free(pin_array *instance)
   *  @brief frees all memory allocated to @p instance
   *
   *  @param instance - pointer to @a pin_array_array struct
   *
   *  Returns
   *    Nothing.
   */

void pin_array_free(pin_array *instance)
{
  int i;

  if (!instance) goto exit;

  for (i = 0; i < instance->n; i++)
    pin_free(instance->item[i]);

  free(instance->item);
  free(instance);

exit:
}

  /**
   *  @fn int pin_array_get_current(pin_array *instance)
   *  @brief returns current index value of @p instance list
   *
   *  @param instance - pointer to @a pin_array struct
   *
   *  @return current index value of @a pin_array
   */

int pin_array_get_current(pin_array *instance)
{
  return instance ? instance->current : 0;
}

  /**
   *  @fn void pin_array_add(pin_array *instance, pin *item)
   *  @brief adds @p item to @p instance list
   *
   *  @param instance - pointer to @a pin_array struct
   *  @param item - pointer to @a pin struct
   *
   *  @par Returns
   *  Nothing.
   */

void pin_array_add(pin_array *instance, pin *item)
{
  void *tmp = NULL;

  if (!instance || !item) return;

  tmp = realloc(instance->item, sizeof(pin *) * (instance->n + 1));
  if (!tmp) return;

  instance->item = tmp;
  instance->item[instance->n] = pin_dup(item);

  ++instance->n;
}

  /**
   *  @fn void pin_array_remove(pin_array *instance, int index)
   *  @brief removes item at @p index from @p instance list
   *
   *  @param instance - pointer to @a pin_array struct
   *  @param index - index into instance->item array
   *
   *  @par Returns
   *  Nothing.
   */

void pin_array_remove(pin_array *instance, int index)
{
  int i;
  void *tmp = NULL;

  if (!instance) return;
  if (index < 0) return;
  if (index >= instance->n) return;

  pin_free(instance->item[index]);

  for (i = index; i < instance->n - 1; i++)
    instance->item[i] = instance->item[i + 1];

  --instance->n;

  tmp = realloc(instance->item, sizeof(pin *) * instance->n);
  if (!tmp) return;

  instance->item = tmp;
}

  /**
   *  @fn pin *pin_array_first(pin_array *instance)
   *  @brief returns first item in @a pin_array
   *
   *  @param instance - pointer to @a pin_array struct
   *
   *  @return pointer to @a pin on success, NULL on failure
   */

pin *pin_array_first(pin_array *instance)
{
  pin *item = NULL;

  if (!instance) goto exit;
  if (!instance->n) goto exit;

  instance->current = 0;
  item = instance->item[0];

exit:
  return item;
}

  /**
   *  @fn pin *pin_array_next(pin_array *instance)
   *  @brief returns next item in @a pin_array
   *
   *  @param instance - pointer to @a pin_array struct
   *
   *  @return pointer to @a pin on success, NULL on failure
   */

pin *pin_array_next(pin_array *instance)
{
  pin *item = NULL;

  if (!instance) goto exit;
  if (!instance->n) goto exit;

  if (instance->current < 0) instance->current = 0;
  else if (instance->current >= instance->n) instance->current = instance->n - 1;

  ++instance->current;

  if (instance->current >= instance->n)
    instance->current = 0;
  else
    item = instance->item[instance->current];

exit:
  return item;
}

  /**
   *  @fn pin *pin_array_previous(pin_array *instance)
   *  @brief returns previous item in @a pin_array
   *
   *  @param instance - pointer to @a pin_array struct
   *
   *  @return pointer to @a pin on success, NULL on failure
   */

pin *pin_array_previous(pin_array *instance)
{
  pin *item = NULL;

  if (!instance) goto exit;
  if (!instance->n) goto exit;

  if (instance->current < 0) instance->current = 0;
  else if (instance->current >= instance->n) instance->current = instance->n - 1;

  --instance->current;

  if (instance->current < 0)
    instance->current = instance->n - 1;
  else
    item = instance->item[instance->current];

exit:
  return item;
}

  /**
   *  @fn pin *pin_array_last(pin_array *instance)
   *  @brief returns last item in @a pin_array
   *
   *  @param instance - pointer to @a pin_array struct
   *
   *  @return pointer to @a pin on success, NULL on failure
   */

pin *pin_array_last(pin_array *instance)
{
  pin *item = NULL;

  if (!instance) goto exit;
  if (!instance->n) goto exit;

  instance->current = instance->n - 1;
  item = instance->item[instance->current];

exit:
  return item;
}

  /**
   *  @fn pin *pin_array_current(pin_array *instance)
   *  @brief returns current item in @a pin_array
   *
   *  @param instance - pointer to @a pin_array struct
   *
   *  @return pointer to @a pin on success, NULL on failure
   */

pin *pin_array_current(pin_array *instance)
{
  pin *item = NULL;

  if (!instance) goto exit;
  if (!instance->n) goto exit;

  if (instance->current < 0) instance->current = 0;
  if (instance->current >= instance->n) instance->current = instance->n - 1;

  item = instance->item[instance->current];

exit:
  return item;
}

