/*
 *  Copyright 2026 - Patrick Head
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 *  @file shape.c
 *  @brief functions to manage shape data
 *
 *  This file was generated by kahdifire
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include "shape.h"

    /*
     *  Utility functions for enum shape_type
     */

  /**
   *  @fn shape_type shape_shape_type_from_str(char *enum_name)
   *  @brief converts @p enum_name to @a shape_type value
   *
   *  @param enum_name - string version of @a shape_type value
   *
   *  @return @a shape_type value
   */

shape_type shape_shape_type_from_str(char *enum_name)
{
  if (!enum_name) return 0;

  if (!strcmp(enum_name, "shape_type_none")) return shape_type_none;
  else if (!strcmp(enum_name, "shape_type_box")) return shape_type_box;

  return 0;
}

  /**
   *  @fn char *shape_shape_type_to_str(shape_type type)
   *  @brief converts @p type to string value
   *
   *  @param type - shape_type value
   *
   *  @return string version of shape_type value
   */

char *shape_shape_type_to_str(shape_type type)
{
  switch (type)
  {
    case shape_type_none: return "shape_type_none";
    case shape_type_box: return "shape_type_box";
  }

  return "UNKNOWN";
}

    /*
     *  Utility functions for struct shape
     */

  /**
   *  @fn shape *shape_new(void)
   *  @brief creates a new @a struct @a shape
   *
   *  @par Parameters
   *    None.
   *
   *  @return pointer to new @a struct @a shape on success, NULL on failure
   */

shape *shape_new(void)
{
  shape *instance = NULL;

  instance = malloc(sizeof(shape));
  if (instance) memset(instance, 0, sizeof(shape));

  return instance;
}

  /**
   *  @fn shape *shape_dup(shape *instance)
   *  @brief creates a deep copy of @p instance
   *
   *  @param instance - pointer to @a struct @a shape
   *
   *  @return pointer to new @a struct @a shape on success, NULL on failure
   */

shape *shape_dup(shape *instance)
{
  shape *new_instance = NULL;

  if (!instance) goto exit;

  new_instance = shape_new();
  if (!new_instance) goto exit;

  memcpy(new_instance, instance, sizeof(shape));

exit:
  return new_instance;
}

  /**
   *  @fn void shape_free(shape *instance)
   *  @brief frees all memory allocated to @p instance
   *
   *  @param instance - pointer to @a struct @a shape
   *
   *  Returns
   *    Nothing.
   */

void shape_free(shape *instance)
{
  if (!instance) goto exit;

  free(instance);

exit:
}

  /**
   *  @fn char *shape_get_type(shape *instance)
   *  @brief returns value of instance->type
   *
   *  @param instance - pointer to @a shape
   *
   *  @return shape_type
   */

shape_type shape_get_type(shape *instance)
{
  return instance ? instance->type : shape_type_none;
}

  /**
   *  @fn void shape_set_type(shape *instance, shape_type type)
   *  @brief sets value of instance->type
   *
   *  @param instance - pointer to @a shape
   *  @param type - new @ shape_type
   *
   *  @par Returns
   *    Nothing.
   */

void shape_set_type(shape *instance, shape_type type)
{
  if (!instance) return;

  instance->type = type;
}

  /**
   *  @fn bool shape_get_filled(shape *instance)
   *  @brief returns value of instance->filled
   *
   *  @param instance - pointer to @a shape
   *
   *  @return bool on success, 0 or NULL on failure
   */

bool shape_get_filled(shape *instance)
{
  return instance ? instance->filled : 0;
}

  /**
   *  @fn void shape_set_filled(shape *instance, bool filled)
   *  @brief sets value of instance->filled
   *
   *  @param instance - pointer to @a shape
   *  @param filled - new value
   *
   *  @par Returns
   *    Nothing.
   */

void shape_set_filled(shape *instance, bool filled)
{
  if (!instance) return;

  if (instance) instance->filled = filled;
}

  /**
   *  @fn char *shape_type_to_string(shape_type st)
   *  @brief convert @a shape_type value to string
   *
   *  @param st - @a shape_type value
   *
   *  @return string representation of @a shape_type value
   */

char *shape_type_to_string(shape_type st)
{
  switch (st)
  {
    case shape_type_none: return "NONE";
    case shape_type_box: return "BOX";

    default: return "NONE";
  }

  return "NONE";
}

  /**
   *  @fn shape_type shape_type_from_string(char *s)
   *  @brief convert string to @a shape_type value
   *
   *  @param s - string representation of @a shape_type value
   *
   *  @return @a shape_type value
   */

shape_type shape_type_from_string(char *s)
{
  shape_type type = shape_type_none;

  if (!s) goto exit;

  if (!strcmp(s, "box")) type = shape_type_box;

exit:
  return type;
}
    /*
     *  Utility functions for struct shape_array
     */

  /**
   *  @fn shape_array *shape_array_new(void)
   *  @brief creates a new @a shape_array struct
   *
   *  @par Parameters
   *    None.
   *
   *  @return pointer to new @a shape_array on success, NULL on failure
   */

shape_array *shape_array_new(void)
{
  shape_array *instance = NULL;

  instance = malloc(sizeof(shape_array));
  if (instance) memset(instance, 0, sizeof(shape_array));

  return instance;
}

  /**
   *  @fn shape_array *shape_array_dup(shape_array *instance)
   *  @brief creates a deep copy of @a shape_array struct
   *
   *  @param instance - pointer to shape_array struct
   *
   *  @return pointer to new @a shape_array on success, NULL on failure
   */

shape_array *shape_array_dup(shape_array *instance)
{
  shape_array *new_instance = NULL;
  int i;

  if (!instance) goto exit;

  new_instance = shape_array_new();
  if (!new_instance) goto exit;

  for (i = 0; i < instance->n; i++)
    shape_array_add(new_instance, instance->item[i]);

exit:
  return new_instance;
}

  /**
   *  @fn void shape_array_free(shape_array *instance)
   *  @brief frees all memory allocated to @p instance
   *
   *  @param instance - pointer to @a shape_array_array struct
   *
   *  Returns
   *    Nothing.
   */

void shape_array_free(shape_array *instance)
{
  int i;

  if (!instance) goto exit;

  for (i = 0; i < instance->n; i++)
    shape_free(instance->item[i]);

  free(instance->item);
  free(instance);

exit:
}

  /**
   *  @fn int shape_array_get_current(shape_array *instance)
   *  @brief returns current index value of @p instance list
   *
   *  @param instance - pointer to @a shape_array struct
   *
   *  @return current index value of @a shape_array
   */

int shape_array_get_current(shape_array *instance)
{
  return instance ? instance->current : 0;
}

  /**
   *  @fn void shape_array_add(shape_array *instance, shape *item)
   *  @brief adds @p item to @p instance list
   *
   *  @param instance - pointer to @a shape_array struct
   *  @param item - pointer to @a shape struct
   *
   *  @par Returns
   *  Nothing.
   */

void shape_array_add(shape_array *instance, shape *item)
{
  void *tmp = NULL;

  if (!instance || !item) return;

  tmp = realloc(instance->item, sizeof(shape *) * (instance->n + 1));
  if (!tmp) return;

  instance->item = tmp;
  instance->item[instance->n] = shape_dup(item);

  ++instance->n;
}

  /**
   *  @fn void shape_array_remove(shape_array *instance, int index)
   *  @brief removes item at @p index from @p instance list
   *
   *  @param instance - pointer to @a shape_array struct
   *  @param index - index into instance->item array
   *
   *  @par Returns
   *  Nothing.
   */

void shape_array_remove(shape_array *instance, int index)
{
  int i;
  void *tmp = NULL;

  if (!instance) return;
  if (index < 0) return;
  if (index >= instance->n) return;

  shape_free(instance->item[index]);

  for (i = index; i < instance->n - 1; i++)
    instance->item[i] = instance->item[i + 1];

  --instance->n;

  tmp = realloc(instance->item, sizeof(shape *) * instance->n);
  if (!tmp) return;

  instance->item = tmp;
}

  /**
   *  @fn shape *shape_array_first(shape_array *instance)
   *  @brief returns first item in @a shape_array
   *
   *  @param instance - pointer to @a shape_array struct
   *
   *  @return pointer to @a shape on success, NULL on failure
   */

shape *shape_array_first(shape_array *instance)
{
  shape *item = NULL;

  if (!instance) goto exit;
  if (!instance->n) goto exit;

  instance->current = 0;
  item = instance->item[0];

exit:
  return item;
}

  /**
   *  @fn shape *shape_array_next(shape_array *instance)
   *  @brief returns next item in @a shape_array
   *
   *  @param instance - pointer to @a shape_array struct
   *
   *  @return pointer to @a shape on success, NULL on failure
   */

shape *shape_array_next(shape_array *instance)
{
  shape *item = NULL;

  if (!instance) goto exit;
  if (!instance->n) goto exit;

  if (instance->current < 0) instance->current = 0;
  else if (instance->current >= instance->n) instance->current = instance->n - 1;

  ++instance->current;

  if (instance->current >= instance->n)
    instance->current = 0;
  else
    item = instance->item[instance->current];

exit:
  return item;
}

  /**
   *  @fn shape *shape_array_previous(shape_array *instance)
   *  @brief returns previous item in @a shape_array
   *
   *  @param instance - pointer to @a shape_array struct
   *
   *  @return pointer to @a shape on success, NULL on failure
   */

shape *shape_array_previous(shape_array *instance)
{
  shape *item = NULL;

  if (!instance) goto exit;
  if (!instance->n) goto exit;

  if (instance->current < 0) instance->current = 0;
  else if (instance->current >= instance->n) instance->current = instance->n - 1;

  --instance->current;

  if (instance->current < 0)
    instance->current = instance->n - 1;
  else
    item = instance->item[instance->current];

exit:
  return item;
}

  /**
   *  @fn shape *shape_array_last(shape_array *instance)
   *  @brief returns last item in @a shape_array
   *
   *  @param instance - pointer to @a shape_array struct
   *
   *  @return pointer to @a shape on success, NULL on failure
   */

shape *shape_array_last(shape_array *instance)
{
  shape *item = NULL;

  if (!instance) goto exit;
  if (!instance->n) goto exit;

  instance->current = instance->n - 1;
  item = instance->item[instance->current];

exit:
  return item;
}

  /**
   *  @fn shape *shape_array_current(shape_array *instance)
   *  @brief returns current item in @a shape_array
   *
   *  @param instance - pointer to @a shape_array struct
   *
   *  @return pointer to @a shape on success, NULL on failure
   */

shape *shape_array_current(shape_array *instance)
{
  shape *item = NULL;

  if (!instance) goto exit;
  if (!instance->n) goto exit;

  if (instance->current < 0) instance->current = 0;
  if (instance->current >= instance->n) instance->current = instance->n - 1;

  item = instance->item[instance->current];

exit:
  return item;
}

