/*
 *  Copyright 2026 - Patrick Head
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 *  @file slot.c
 *  @brief functions to manage slot data
 *
 *  This file was generated by kahdifire
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include "slot.h"

    /*
     *  Utility functions for struct slot
     */

  /**
   *  @fn slot *slot_new(void)
   *  @brief creates a new @a struct @a slot
   *
   *  @par Parameters
   *    None.
   *
   *  @return pointer to new @a struct @a slot on success, NULL on failure
   */

slot *slot_new(void)
{
  slot *instance = NULL;

  instance = malloc(sizeof(slot));
  if (instance) memset(instance, 0, sizeof(slot));

  instance->attributes = attribute_array_new();
  instance->pins = pin_array_new();

  return instance;
}

  /**
   *  @fn slot *slot_dup(slot *instance)
   *  @brief creates a deep copy of @p instance
   *
   *  @param instance - pointer to @a struct @a slot
   *
   *  @return pointer to new @a struct @a slot on success, NULL on failure
   */

slot *slot_dup(slot *instance)
{
  slot *new_instance = NULL;

  if (!instance) goto exit;

  new_instance = slot_new();
  if (!new_instance) goto exit;

  memcpy(new_instance, instance, sizeof(slot));

  if (instance->label)
    new_instance->label = strdup(instance->label);

  if (instance->name)
    new_instance->name = strdup(instance->name);

  new_instance->attributes = attribute_array_dup(instance->attributes);

exit:
  return new_instance;
}

  /**
   *  @fn void slot_free(slot *instance)
   *  @brief frees all memory allocated to @p instance
   *
   *  @param instance - pointer to @a struct @a slot
   *
   *  Returns
   *    Nothing.
   */

void slot_free(slot *instance)
{
  if (!instance) goto exit;

  if (instance->label)
    free(instance->label);

  if (instance->attributes) attribute_array_free(instance->attributes);

  free(instance);

exit:
}

  /**
   *  @fn char *slot_get_name(slot *instance)
   *  @brief returns value of instance->name
   *
   *  @param instance - pointer to @a slot
   *
   *  @return char* on success, 0 or NULL on failure
   */

char *slot_get_name(slot *instance)
{
  return instance ? instance->name : NULL;
}

  /**
   *  @fn void slot_set_name(slot *instance, char *name)
   *  @brief sets value of instance->name
   *
   *  @param instance - pointer to @a slot
   *  @param name - new value
   *
   *  @par Returns
   *    Nothing.
   */

void slot_set_name(slot *instance, char *name)
{
  if (!instance) return;

  if (instance->name) free(instance->name);
  instance->name = NULL;
  if (name) instance->name = strdup(name);
}

  /**
   *  @fn char *slot_get_shape(slot *instance)
   *  @brief returns value of instance->shape
   *
   *  @param instance - pointer to @a slot
   *
   *  @return pointer to a @a shape
   */

shape *slot_get_shape(slot *instance)
{
  return instance ? &instance->shape : NULL;
}

  /**
   *  @fn void slot_set_shape(slot *instance,
   *                                    slot_shape shape)
   *  @brief sets value of instance->shape
   *
   *  @param instance - pointer to @a slot
   *  @param shape - new @ slot_shape
   *
   *  @par Returns
   *    Nothing.
   */

void slot_set_shape(slot *instance,
                              shape *new_shape)
{
  if (!instance) return;
  if (!new_shape) return;

  memcpy(&instance->shape, new_shape, sizeof(shape));
}

  /**
   *  @fn pinalign *slot_get_pinalignment(slot *instance, pinalign_side side)
   *  @brief returns @ pinalign for @p side
   *
   *  @param side - @ pinalign_side
   *
   *  @return pointer to @a pinalign
   */

pinalign *slot_get_pinalignment(slot *instance, pinalign_side side)
{
  return instance ? &instance->pinalignment[side] : NULL;
}

  /**
   *  @fn void slot_set_pinalignment(slot *instance, pinalign *pinalignment)
   *  @brief sets pin alignment for @p pinalignment->side
   *
   *  @param instance - pointer to @a slot
   *  @param pin_alignment - pointer to new @ pinalign
   *
   *  @par Returns
   *    Nothing.
   */

void slot_set_pinalignment(slot *instance, pinalign *pinalignment)
{
  if (!instance) return;
  if (!pinalignment) return;

  memcpy(&instance->pinalignment[pinalignment->side],
         pinalignment,
         sizeof (pinalign));
}

  /**
   *  @fn char *slot_get_label(slot *instance)
   *  @brief returns value of instance->label
   *
   *  @param instance - pointer to @a slot
   *
   *  @return char* on success, 0 or NULL on failure
   */

char *slot_get_label(slot *instance)
{
  return instance ? instance->label : NULL;
}

  /**
   *  @fn void slot_set_label(slot *instance, char *label)
   *  @brief sets value of instance->label
   *
   *  @param instance - pointer to @a slot
   *  @param label - new value
   *
   *  @par Returns
   *    Nothing.
   */

void slot_set_label(slot *instance, char *label)
{
  if (!instance) return;

  if (instance->label) free(instance->label);
  instance->label = NULL;
  if (label) instance->label = strdup(label);
}

  /**
   *  @fn int slot_get_width(slot *instance)
   *  @brief returns width of slot outline box
   *
   *  @param instance - pointer to @a slot
   *
   *  @return width of outline box
   */

int slot_get_width(slot *instance)
{
  return instance ? instance->width : 0;
}

  /**
   *  @fn void slot_set_width(slot *instance, unsigned int width)
   *  @brief sets width of slot outline box
   *
   *  @param instance - pointer to @a slot
   *  @param width - new value
   *
   *  @par Returns
   *    Nothing.
   */

void slot_set_width(slot *instance, unsigned int width)
{
  if (instance) instance->width = width;
}

  /**
   *  @fn int slot_get_height(slot *instance)
   *  @brief returns height of slot outline box
   *
   *  @param instance - pointer to @a slot
   *
   *  @return height of outline box
   */

int slot_get_height(slot *instance)
{
  return instance ? instance->height : 0;
}

  /**
   *  @fn void slot_set_height(slot *instance, unsigned int height);
   *  @brief sets height of slot outline box
   *
   *  @param instance - pointer to @a slot
   *  @param height - new value
   *
   *  @par Returns
   *    Nothing.
   */

void slot_set_height(slot *instance, unsigned int height)
{
  if (instance) instance->height = height;
}

  /**
   *  @fn attributes *slot_get_attributes(slot *instance)
   *  @brief returns instance->attributes
   *
   *  @param instance - pointer to @a slot
   *
   *  @return pointer to @a attribute_array
   */

attribute_array *slot_get_attributes(slot *instance)
{
  return instance ? instance->attributes : NULL;
}

  /**
   *  @fn void slot_set_attributes(slot *instance, attribute_array *attributes)
   *  @brief sets instance->attributes to a copy of @p attributes
   *
   *  @param instance - pointer to @a slot
   *  @param attributes - pointer to  @a attribute_array
   *
   *  @par Returns
   *    Nothing.
   */

void slot_set_attributes(slot *instance, attribute_array *attributes)
{
  if (!instance) return;

  if (instance->attributes) attribute_array_free(instance->attributes);

  instance->attributes = attribute_array_dup(attributes);
}

  /**
   *  @fn pins *slot_get_pins(slot *instance)
   *  @brief returns instance->pins
   *
   *  @param instance - pointer to @a slot
   *
   *  @return pointer to @a pin_array
   */

pin_array *slot_get_pins(slot *instance)
{
  return instance ? instance->pins : NULL;
}

  /**
   *  @fn void slot_set_pins(slot *instance, pin_array *pins)
   *  @brief sets instance->pins to a copy of @p pins
   *
   *  @param instance - pointer to @a slot
   *  @param pins - pointer to  @a pin_array
   *
   *  @par Returns
   *    Nothing.
   */

void slot_set_pins(slot *instance, pin_array *pins)
{
  if (!instance) return;

  if (instance->pins) pin_array_free(instance->pins);
  instance->pins = NULL;
  if (pins) instance->pins = pin_array_dup(pins);
}

    /*
     *  Utility functions for struct slot_array
     */

  /**
   *  @fn slot_array *slot_array_new(void)
   *  @brief creates a new @a slot_array struct
   *
   *  @par Parameters
   *    None.
   *
   *  @return pointer to new @a slot_array on success, NULL on failure
   */

slot_array *slot_array_new(void)
{
  slot_array *instance = NULL;

  instance = malloc(sizeof(slot_array));
  if (instance) memset(instance, 0, sizeof(slot_array));

  return instance;
}

  /**
   *  @fn slot_array *slot_array_dup(slot_array *instance)
   *  @brief creates a deep copy of @a slot_array struct
   *
   *  @param instance - pointer to slot_array struct
   *
   *  @return pointer to new @a slot_array on success, NULL on failure
   */

slot_array *slot_array_dup(slot_array *instance)
{
  slot_array *new_instance = NULL;
  int i;

  if (!instance) goto exit;

  new_instance = slot_array_new();
  if (!new_instance) goto exit;

  for (i = 0; i < instance->n; i++)
    slot_array_add(new_instance, instance->item[i]);

exit:
  return new_instance;
}

  /**
   *  @fn void slot_array_free(slot_array *instance)
   *  @brief frees all memory allocated to @p instance
   *
   *  @param instance - pointer to @a slot_array_array struct
   *
   *  Returns
   *    Nothing.
   */

void slot_array_free(slot_array *instance)
{
  int i;

  if (!instance) goto exit;

  for (i = 0; i < instance->n; i++)
    slot_free(instance->item[i]);

  free(instance->item);
  free(instance);

exit:
}

  /**
   *  @fn slot *slot_array_get(slot_array *instance, unsigned int idx)
   *  @brief returns @a slot structure at index in @p instance
   *
   *  @param instance - pointer to @a slot_array struct
   *
   *  @return pointer to @a slot structure, nor NULL on error
   */

slot *slot_array_get(slot_array *instance, unsigned int idx)
{
  slot *sl = NULL;

  if (!instance || (idx >= instance->n)) goto exit;
  if (!instance->item) goto exit;

  sl = instance->item[idx];

exit:
  return sl;
}

  /**
   *  @fn int slot_array_get_current(slot_array *instance)
   *  @brief returns current index value of @p instance list
   *
   *  @param instance - pointer to @a slot_array struct
   *
   *  @return current index value of @a slot_array
   */

int slot_array_get_current(slot_array *instance)
{
  return instance ? instance->current : 0;
}

  /**
   *  @fn void slot_array_add(slot_array *instance, slot *item)
   *  @brief adds @p item to @p instance list
   *
   *  @param instance - pointer to @a slot_array struct
   *  @param item - pointer to @a slot struct
   *
   *  @par Returns
   *  Nothing.
   */

void slot_array_add(slot_array *instance, slot *item)
{
  void *tmp = NULL;

  if (!instance || !item) return;

  tmp = realloc(instance->item, sizeof(slot *) * (instance->n + 1));
  if (!tmp) return;

  instance->item = tmp;
  instance->item[instance->n] = slot_dup(item);

  ++instance->n;
}

  /**
   *  @fn void slot_array_remove(slot_array *instance, int index)
   *  @brief removes item at @p index from @p instance list
   *
   *  @param instance - pointer to @a slot_array struct
   *  @param index - index into instance->item array
   *
   *  @par Returns
   *  Nothing.
   */

void slot_array_remove(slot_array *instance, int index)
{
  int i;
  void *tmp = NULL;

  if (!instance) return;
  if (index < 0) return;
  if (index >= instance->n) return;

  slot_free(instance->item[index]);

  for (i = index; i < instance->n - 1; i++)
    instance->item[i] = instance->item[i + 1];

  --instance->n;

  tmp = realloc(instance->item, sizeof(slot *) * instance->n);
  if (!tmp) return;

  instance->item = tmp;
}

  /**
   *  @fn slot *slot_array_first(slot_array *instance)
   *  @brief returns first item in @a slot_array
   *
   *  @param instance - pointer to @a slot_array struct
   *
   *  @return pointer to @a slot on success, NULL on failure
   */

slot *slot_array_first(slot_array *instance)
{
  slot *item = NULL;

  if (!instance) goto exit;
  if (!instance->n) goto exit;

  instance->current = 0;
  item = instance->item[0];

exit:
  return item;
}

  /**
   *  @fn slot *slot_array_next(slot_array *instance)
   *  @brief returns next item in @a slot_array
   *
   *  @param instance - pointer to @a slot_array struct
   *
   *  @return pointer to @a slot on success, NULL on failure
   */

slot *slot_array_next(slot_array *instance)
{
  slot *item = NULL;

  if (!instance) goto exit;
  if (!instance->n) goto exit;

  if (instance->current < 0) instance->current = 0;
  else if (instance->current >= instance->n) instance->current = instance->n - 1;

  ++instance->current;

  if (instance->current >= instance->n)
    instance->current = 0;
  else
    item = instance->item[instance->current];

exit:
  return item;
}

  /**
   *  @fn slot *slot_array_previous(slot_array *instance)
   *  @brief returns previous item in @a slot_array
   *
   *  @param instance - pointer to @a slot_array struct
   *
   *  @return pointer to @a slot on success, NULL on failure
   */

slot *slot_array_previous(slot_array *instance)
{
  slot *item = NULL;

  if (!instance) goto exit;
  if (!instance->n) goto exit;

  if (instance->current < 0) instance->current = 0;
  else if (instance->current >= instance->n) instance->current = instance->n - 1;

  --instance->current;

  if (instance->current < 0)
    instance->current = instance->n - 1;
  else
    item = instance->item[instance->current];

exit:
  return item;
}

  /**
   *  @fn slot *slot_array_last(slot_array *instance)
   *  @brief returns last item in @a slot_array
   *
   *  @param instance - pointer to @a slot_array struct
   *
   *  @return pointer to @a slot on success, NULL on failure
   */

slot *slot_array_last(slot_array *instance)
{
  slot *item = NULL;

  if (!instance) goto exit;
  if (!instance->n) goto exit;

  instance->current = instance->n - 1;
  item = instance->item[instance->current];

exit:
  return item;
}

  /**
   *  @fn slot *slot_array_current(slot_array *instance)
   *  @brief returns current item in @a slot_array
   *
   *  @param instance - pointer to @a slot_array struct
   *
   *  @return pointer to @a slot on success, NULL on failure
   */

slot *slot_array_current(slot_array *instance)
{
  slot *item = NULL;

  if (!instance) goto exit;
  if (!instance->n) goto exit;

  if (instance->current < 0) instance->current = 0;
  if (instance->current >= instance->n) instance->current = instance->n - 1;

  item = instance->item[instance->current];

exit:
  return item;
}

